In [5]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.optimizers import Adam

In [8]:
from keras.datasets import fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 2s 0us/step


In [9]:
train_labels.reshape(len(train_labels),1)

array([[9],
       [0],
       [0],
       ...,
       [3],
       [0],
       [5]], dtype=uint8)

In [10]:
from keras.utils import to_categorical
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)


In [11]:
network=Sequential()
# 4  HIDDEN LAYERS AND 10 OUTPUTS
network.add(Dense(784,input_dim=train_images.shape[1],activation='relu'))
network.add(Dropout(0.5))
network.add(Dense(2048,activation='relu'))
network.add(Dropout(0.5))
network.add((Dense(2048,activation='relu')))
network.add(Dropout(0.5))
network.add((Dense(2048,activation='relu')))
network.add(Dropout(0.5))
network.add(Dense(10,activation='softmax'))

network.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

network.fit(train_images,train_labels,epochs=5,batch_size=128)

test_loss,test_accuracy=network.evaluate(test_images,test_labels)

print("Test Accuracy:",test_accuracy)


Epoch 1/5
469/469 [==============================] - 128s 270ms/step - loss: 0.6615 - accuracy: 0.7617
Epoch 2/5
469/469 [==============================] - 146s 310ms/step - loss: 0.5097 - accuracy: 0.8194
Epoch 3/5
469/469 [==============================] - 130s 278ms/step - loss: 0.4806 - accuracy: 0.8296
Epoch 4/5
469/469 [==============================] - 117s 250ms/step - loss: 0.4618 - accuracy: 0.8361
Epoch 5/5
313/313 [==============================] - 5s 15ms/step - loss: 0.4024 - accuracy: 0.8601
Test Accuracy: 0.8600999712944031


In [12]:
pred=network.predict(test_images)

313/313 [==============================] - 5s 15ms/step


In [13]:
test_images.shape

(10000, 784)

In [14]:
np.round(pred[0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [15]:
(train_img, trainl), (test_img, test_l) = mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [16]:
train_img

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [17]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [18]:
my_array = np.zeros((3, 4, 2))

In [19]:
my_array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
a=my_array.reshape(3,4*2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
pred

array([[1.36328119e-04, 8.32377773e-05, 6.02680157e-05, ...,
        1.45214692e-01, 1.34545646e-03, 8.21546674e-01],
       [3.14417266e-04, 7.80981190e-06, 9.73776996e-01, ...,
        1.73588099e-09, 2.15936270e-05, 6.73882772e-09],
       [1.70841698e-17, 1.00000000e+00, 7.65783455e-21, ...,
        4.86552265e-34, 1.30977184e-20, 4.78082618e-30],
       ...,
       [5.37501307e-07, 1.03723662e-11, 1.94883114e-07, ...,
        3.59395050e-13, 9.99997973e-01, 2.91644882e-13],
       [1.10530904e-10, 1.00000000e+00, 1.26919623e-12, ...,
        4.65047564e-20, 3.66970516e-12, 8.69825578e-18],
       [1.27816456e-05, 9.87330623e-07, 5.10472910e-06, ...,
        3.90253104e-02, 5.86176699e-04, 2.46173167e-03]], dtype=float32)

In [ ]:
history=network.fit(train_images,train_labels,validation_data=(test_images,test_labels),epochs=60,batch_size=128)
from keras.utils.vis_utils import plot_model
train_acc=history.history['accuracy']
val_acc=history.history['val_accuracy']

import matplotlib.pyplot as plt
plt.plot(train_acc,label='training accuracy')
plt.plot(val_acc,label='Validation accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()


Epoch 1/60
469/469 [==============================] - 245s 523ms/step - loss: 0.4426 - accuracy: 0.8439 - val_loss: 0.4066 - val_accuracy: 0.8570
Epoch 2/60
469/469 [==============================] - 262s 559ms/step - loss: 0.4380 - accuracy: 0.8443 - val_loss: 0.4141 - val_accuracy: 0.8508
Epoch 3/60
469/469 [==============================] - 272s 579ms/step - loss: 0.4305 - accuracy: 0.8504 - val_loss: 0.3896 - val_accuracy: 0.8657
Epoch 4/60
469/469 [==============================] - 286s 610ms/step - loss: 0.4212 - accuracy: 0.8511 - val_loss: 0.3783 - val_accuracy: 0.8655
Epoch 5/60
469/469 [==============================] - 258s 549ms/step - loss: 0.4234 - accuracy: 0.8513 - val_loss: 0.4107 - val_accuracy: 0.8613
Epoch 6/60
469/469 [==============================] - 244s 520ms/step - loss: 0.4180 - accuracy: 0.8524 - val_loss: 0.3825 - val_accuracy: 0.8669
Epoch 7/60
469/469 [==============================] - 253s 540ms/step - loss: 0.4122 - accuracy: 0.8554 - val_loss: 0.3960 -